{{- if .Values.streamsets.crdEnabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sdcs.streamsets.k8s.io
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": before-hook-creation
scope: Namespaced
spec:
  group: streamsets.k8s.io
  version: v1
  names:
    kind: SdcCustomResource
    plural: sdcs
    singular: sdc
{{- end }}