kind: Secret
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-credentials
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  apiToken: {{required "A Control Agent API token is required!" .Values.streamsets.api.token | b64enc }}
