{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "transformer.fullname" . }}
  labels:
    app: {{ include "transformer.name" . }}
    chart: {{ include "transformer.chart" . }}
    release: {{ .Release.Name }}
    managed-by: {{ .Release.Service }}
  annotations:
    {{- if (ne "/" .Values.ingress.path) }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- if and (.Values.ingress.host) (.Values.ingress.domain) }}
    - host: {{ .Values.ingress.host }}.{{ .Values.ingress.domain }}
    {{- else }}
    - host: ""
    {{- end }}
      http:
        paths:
          {{- if (eq "/" .Values.ingress.path) }}
          - path: /
          {{- else }}
          - path: {{ .Values.ingress.path }}(/|$)(.*)
          {{- end }}
            backend:
              serviceName: {{ include "transformer.fullname" . }}
              servicePort: 19635
{{- end }}
