apiVersion: v1
kind: Service
metadata:
  name: {{ include "transformer.fullname" . }}
  labels:
    app: {{ include "transformer.name" . }}
    chart: {{ include "transformer.chart" . }}
    release: {{ .Release.Name }}
    managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 19635
      targetPort: 19630
      protocol: TCP
  selector:
    app: {{ include "transformer.name" . }}
