{{- if .Values.controlHub.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "transformer.fullname" . }}
  labels:
    app: {{ include "transformer.name" . }}
    chart: {{ include "transformer.chart" . }}
    release: {{ .Release.Name }}
    managed-by: {{ .Release.Service }}
type: Opaque
data:
  apiToken: {{ required "A StreamSets Transformer API token is required!" .Values.controlHub.token | b64enc }}
{{- end}}
