{{- if .Values.transformer.truststoreFile }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "transformer.fullname" . }}-cert
  labels:
    app: {{ include "transformer.name" . }}
    chart: {{ include "transformer.chart" . }}
    release: {{ .Release.Name }}
    managed-by: {{ .Release.Service }}
type: Opaque
data:
  truststore.jks: {{ .Files.Get .Values.transformer.truststoreFile | b64enc }}
{{- end}}
